services:
  schedule-db:
    container_name: schedule-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a_yYIY%4M7aGbl!
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - schedule
    healthcheck:
      # Добавлено для проверки состояния базы данных
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 5

  schedule-web:
    container_name: schedule-web
    image: nginx
    restart: always
    volumes:
      - ./web/kitek/dist/:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - schedule

  schedule-api:
    container_name: schedule-api
    build: api/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      schedule-db:
        condition: service_healthy
    volumes:
      - /home/xaori/schedule_backend/api/media/:/app/media
    networks:
      - schedule

  glances:
    image: nicolargo/glances
    container_name: glances
    restart: unless-stopped
    pid: host
    ports:
      - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/mnt:ro
    command: glances -w

networks:
  schedule:
    external: true
    name: schedule
    driver: bridge
