services:
  redis:
    image: redis:alpine
    container_name: omsktec-redis
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    image: postgres:latest
    container_name: omsktec-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 2s
      timeout: 1s
      retries: 5

  api:
    container_name: omsktec-api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-dev}
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./media
        target: /app/media
      - type: bind
        source: ./static
        target: /app/static
      - type: bind
        source: ./
        target: /app
        read_only: ${READ_ONLY_CODE:-false}
    profiles:
      - dev
      - prod