services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a_yYIY%4M7aGbl!
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main
    healthcheck:
      # Добавлено для проверки состояния базы данных
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 5

  # web:
  #   container_name: web
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./web/kitek/dist/:/usr/share/nginx/html:ro
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NGINX_PORT=80
  #   networks:
  #     - main

  api:
    container_name: api
    build: api/
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/xaori/schedule_backend/api/media/:/app/media
      - /home/xaori/schedule_backend/api/static/:/app/static
    networks:
      - main



networks:
  main:
    external: true
    name: main
    driver: bridge
