services:
  schedule-db:
    container_name: schedule-db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: a_yYIY%4M7aGbl!
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - schedule
    healthcheck:  # Добавлено для проверки состояния базы данных
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5

  schedule-web:
    container_name: schedule-web
    image: nginx
    volumes:
     - ./web:/usr/share/nginx/html:ro
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    networks:
      - schedule

  schedule-bot:
    container_name: schedule-bot
    build: bot/
    depends_on:
      schedule-db:
        condition: service_healthy 
    networks:
      - schedule

  schedule-api:
    container_name: schedule-api
    build: api/
    ports:
      - "8000:8000"
    depends_on:
      schedule-db:
        condition: service_healthy 
    volumes:
      - /home/xaori/schedule_backend/api/media/:/app/media  
    networks:
      - schedule
    
  schedule-swagger:
    container_name: schedule-swagger
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8079:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger/swagger.yaml
    networks:
      - schedule

networks:
  schedule:
    external: true
    name: schedule
    driver: bridge