# Generated by Django 5.2.4 on 2025-07-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='login',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
