# Generated by Django 5.2.4 on 2025-08-14 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=16, verbose_name='Группа')),
                ('requested_by', models.CharField(max_length=150, verbose_name='Требуется для')),
                ('quantity', models.IntegerField(verbose_name='Колличество')),
                ('status', models.CharField(choices=[('AW', 'В работе'), ('RY', 'Готово')], default='AW', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
            },
        ),
    ]
