# Generated by Django 5.2.4 on 2025-07-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RustoreVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionName', models.CharField(max_length=50, unique=True)),
                ('versionCode', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['-versionCode'],
            },
        ),
    ]
