# Generated by Django 6.0.1 on 2026-01-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_fcmtoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'verbose_name': 'Токен уведомлений', 'verbose_name_plural': 'Токены уведомлений'},
        ),
    ]
