"""
Django settings for schedule project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


dotenv_path = os.path.join(os.path.dirname(__file__), "..", ".env")

config = load_dotenv(dotenv_path)
key = os.getenv("SECRET_KEY")
host = os.getenv("POSTGRES_HOST")
user = os.getenv("POSTGRES_USER")
password = os.getenv("POSTGRES_PASSWORD")
name = os.getenv("POSTGRES_DB_NAME")

REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT = os.getenv('REDIS_PORT', 6379)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    # Красивая админка
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    # Приложения проекта
    "schedule.apps.ScheduleConfig",
    "notification.apps.NotificationConfig",
    "rustore.apps.RustoreConfig",
    "corsheaders",
    "ninja",
    'import_export',
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CSRF_TRUSTED_ORIGINS = [
    "https://147.45.158.220",
    "http://147.45.158.220",
    "https://app.omsktec.ru",
    "http://localhost:8000"
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-client-time",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'templates'),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Omsk"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


UNFOLD = {
    "SITE_TITLE": "Расписание КИТЭКа",
    "SITE_HEADER": "Расписания КИТЭКа",
    "SITE_SUBHEADER": "Административная панель",

    "BORDER_RADIUS": "12px",
    "COLORS": {
        "base": {
            "50":  "oklch(98.8% 0.003 254.6)",
            "100": "oklch(97.1% 0.006 254.6)",
            "200": "oklch(92.4% 0.009 254.1)",
            "300": "oklch(86.5% 0.013 253.8)",
            "400": "oklch(76.0% 0.018 255.4)",
            "500": "oklch(60.0% 0.022 256.2)",
            "600": "oklch(47.5% 0.022 255.8)",
            "700": "oklch(37.5% 0.020 257.0)",
            "800": "oklch(27.5% 0.018 258.0)",
            "900": "oklch(20.5% 0.016 259.0)",
            "950": "oklch(13.5% 0.013 260.0)",
        },

        "primary": {
            "50":  "oklch(97.0% 0.014 254.6)",
            "100": "oklch(93.2% 0.032 255.6)",
            "200": "oklch(88.2% 0.059 254.1)",
            "300": "oklch(80.9% 0.105 251.8)",
            "400": "oklch(70.7% 0.165 254.6)",
            "500": "oklch(57.2% 0.185 258.0)",
            "600": "oklch(48.5% 0.175 261.5)",
            "700": "oklch(40.1% 0.152 263.8)",
            "800": "oklch(32.4% 0.115 265.2)",
            "900": "oklch(25.8% 0.082 266.1)",
            "950": "oklch(17.2% 0.053 268.0)",
        },

        "font": {
            "subtle-light":    "var(--color-base-500)",
            "subtle-dark":     "var(--color-base-400)",
            "default-light":   "var(--color-base-600)",
            "default-dark":    "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark":  "var(--color-base-100)",
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,

        "navigation": [
            {
                "title": _("Главное"),
                "icon": "dashboard_customize",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "analytics",
                        "link": reverse_lazy("admin:index"),
                        "badge_variant": "info",
                        "badge_style": "solid",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Загрузить расписание"),
                        "icon": "download",
                        "link": "/api/admin/add/",
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("Модели"),
                "icon": "widgets",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Файлы"),
                        "icon": "files",
                        "link": reverse_lazy("admin:schedule_schedulefile_changelist"),
                        "badge_variant": "info",
                        "badge_style": "solid",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Расписание звонков"),
                        "icon": "timer",
                        "link": reverse_lazy("admin:schedule_scheduletimetype_changelist"),
                        "badge_variant": "info",
                        "badge_style": "solid",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Админы"),
                "icon": "admin_panel_settings",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Группы"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "badge_variant": "info",
                        "badge_style": "solid",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Пользователи"),
                        "icon": "supervised_user_circle",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "badge_variant": "info",
                        "badge_style": "solid",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    }
}

