# Generated by Django 5.2.4 on 2025-08-29 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('ascii_name', models.CharField(blank=True, max_length=255)),
                ('is_teacher', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('schedule_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfBell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='08:45', help_text='Время начала первой пары')),
                ('lesson', models.PositiveIntegerField(default=90, help_text='Врема пары')),
                ('use_curator_hour', models.BooleanField(default=True, help_text='Включать кураторский час по понедельникам')),
                ('curator_hour', models.PositiveIntegerField(default=40, help_text='Время кураторского часа')),
                ('lunch_break_offset', models.PositiveIntegerField(default=5, help_text='Смещение обеденного перерыва, по понедельникам')),
                ('lunch_break', models.PositiveIntegerField(default=30, help_text='Время обеденного перерыва')),
                ('break_after_1', models.PositiveIntegerField(default=10, help_text='Перемена после первой пары')),
                ('break_after_2', models.PositiveIntegerField(default=10, help_text='Перемена после второй пары')),
                ('break_after_3', models.PositiveIntegerField(default=10, help_text='Перемена после третьей пары')),
                ('break_after_4', models.PositiveIntegerField(default=10, help_text='Перемена после четвертой пары')),
                ('break_after_5', models.PositiveIntegerField(default=5, help_text='Перемена после пятой пары')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='schedule.client')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.scheduleday')),
            ],
            options={
                'ordering': ['title', 'number'],
            },
        ),
    ]
