# Generated by Django 5.2.5 on 2025-09-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ascii_name',
        ),
    ]
