# Generated by Django 5.2.7 on 2025-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_client_ascii_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeofbell',
            name='lunch_break_offset',
        ),
        migrations.AddField(
            model_name='timeofbell',
            name='first_half',
            field=models.PositiveIntegerField(default=30, help_text='Время первой части пары'),
        ),
        migrations.AddField(
            model_name='timeofbell',
            name='lesson_saturday',
            field=models.PositiveIntegerField(default=70, help_text='Врема пары в субботу'),
        ),
        migrations.AddField(
            model_name='timeofbell',
            name='lunch_break_monday',
            field=models.PositiveIntegerField(default=35, help_text='Смещение обеденного перерыва, по понедельникам'),
        ),
        migrations.AddField(
            model_name='timeofbell',
            name='lunch_break_saturday',
            field=models.PositiveIntegerField(default=25, help_text='Смещение обеденного перерыва, по субботам'),
        ),
        migrations.AddField(
            model_name='timeofbell',
            name='second_half',
            field=models.PositiveIntegerField(default=40, help_text='Время второй части пары'),
        ),
    ]
