# Generated by Django 5.2.7 on 2025-11-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_timeofbell_lunch_break_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ascii_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='timeofbell',
            name='first_half',
            field=models.PositiveIntegerField(default=40, help_text='Время первой части пары'),
        ),
        migrations.AlterField(
            model_name='timeofbell',
            name='second_half',
            field=models.PositiveIntegerField(default=30, help_text='Время второй части пары'),
        ),
    ]
