# Generated by Django 5.2.7 on 2025-11-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_client_ascii_name_alter_timeofbell_first_half_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ascii_name',
        ),
    ]
