# Generated by Django 5.2.10 on 2026-01-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_client_ascii_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveSmallIntegerField(help_text='Номер пары (1-7)')),
                ('display_text', models.CharField(help_text='Текст для вывода.', max_length=50)),
            ],
            options={
                'ordering': ['schedule_type', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Уникальный код, например 'lower_mon'", unique=True)),
                ('name', models.CharField(help_text='Название для админки', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeOfBell',
        ),
        migrations.AddField(
            model_name='bell',
            name='schedule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bells', to='schedule.scheduletimetype'),
        ),
        migrations.AlterUniqueTogether(
            name='bell',
            unique_together={('schedule_type', 'lesson_number')},
        ),
    ]
