# Generated by Django 6.0.1 on 2026-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_bell_scheduletimetype_delete_timeofbell_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bell',
            options={'ordering': ['schedule_type', 'lesson_number'], 'verbose_name': 'Звонки', 'verbose_name_plural': 'Звонки'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title', 'number'], 'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterModelOptions(
            name='scheduleday',
            options={'ordering': ['date'], 'verbose_name': 'День расписания', 'verbose_name_plural': 'Дни расписания'},
        ),
        migrations.AlterModelOptions(
            name='schedulefile',
            options={'verbose_name': 'Файл с расписанием', 'verbose_name_plural': 'Файлы с расписанием'},
        ),
        migrations.AlterModelOptions(
            name='scheduletimetype',
            options={'verbose_name': 'Расписание звонков', 'verbose_name_plural': 'Расписания звонков'},
        ),
        migrations.AlterField(
            model_name='bell',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(help_text='Номер пары (1-7)', verbose_name='№ пары'),
        ),
    ]
