# Generated by Django 5.2.1 on 2025-06-30 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lesson_options_rename_name_client_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
