# Generated by Django 5.2.1 on 2025-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_client_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ascii_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
