# Generated by Django 5.2.1 on 2025-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulefile',
            name='date',
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
