# Generated by Django 5.1.3 on 2024-11-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('schedule', 'number', 'title', 'type', 'partner', 'location')},
        ),
    ]
