# Generated by Django 5.2.1 on 2025-06-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title', 'number']},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='schedulefile',
            old_name='name',
            new_name='file_name',
        ),
    ]
