# Generated by Django 5.1.3 on 2024-12-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='client',
        ),
    ]
