# Generated by Django 5.1.3 on 2024-11-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0002_alter_classes_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together=set(),
        ),
    ]
