# Generated by Django 5.1.3 on 2025-01-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0002_alter_client_client_name_alter_itemlesson_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
