# Generated by Django 5.1.3 on 2024-12-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0002_remove_users_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
