# Generated by Django 5.1.3 on 2024-12-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0003_users_is_super_admin_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_super_admin',
        ),
    ]
