# Generated by Django 5.1.4 on 2025-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0003_alter_client_is_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client_name']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='itemlesson',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
