# Generated by Django 5.1.3 on 2024-12-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0004_remove_users_is_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
