# Generated by Django 5.1.4 on 2025-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0004_alter_client_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_created=True)),
                ('file_name', models.CharField(max_length=255)),
                ('schedule_file', models.FileField(upload_to='')),
            ],
        ),
    ]
