# Generated by Django 5.1.4 on 2025-02-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0005_schedulefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulefile',
            name='upload_time',
        ),
    ]
