# Generated by Django 5.1.3 on 2024-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0005_alter_users_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
